"""add_weather_data

Revision ID: 32ed282acd5a
Revises: adaa0efe724c
Create Date: 2026-05-27 01:31:21.905488

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32ed282acd5a"
down_revision: Union[str, Sequence[str], None] = "adaa0efe724c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_data",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "city",
            sa.Enum(
                "BUCHAREST",
                "CLUJ_NAPOCA",
                "TIMISOARA",
                "IASI",
                "CONSTANTA",
                "BRASOV",
                "GALATI",
                "PLOIESTI",
                "ORADEA",
                "BACAU",
                name="romaniancity",
            ),
            nullable=False,
        ),
        sa.Column(
            "provider", sa.Enum("OPENMETEO", name="weatherdataprovider"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("temperature_2m", sa.Float(), nullable=False),
        sa.Column("wind_speed_10m", sa.Float(), nullable=False),
        sa.Column("shortwave_radiation", sa.Float(), nullable=False),
        sa.Column("precipitation", sa.Float(), nullable=False),
        sa.Column("apparent_temperature", sa.Float(), nullable=False),
        sa.Column("relative_humidity_2m", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("timestamp", "city", "provider"),
    )

    op.execute("SELECT create_hypertable('weather_data', 'timestamp')")

    op.create_index(
        "idx_weather_provider_time_city",
        "weather_data",
        ["provider", "city", sa.literal_column("timestamp DESC")],
        unique=True,
    )
    op.create_index(
        op.f("ix_weather_data_timestamp"), "weather_data", ["timestamp"], unique=False
    )
    op.drop_index(
        op.f("energy_generation_timestamp_idx"), table_name="energy_generation"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("energy_generation_timestamp_idx"),
        "energy_generation",
        [sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.drop_index(op.f("ix_weather_data_timestamp"), table_name="weather_data")
    op.drop_index("idx_weather_provider_time_city", table_name="weather_data")
    op.drop_table("weather_data")
    # ### end Alembic commands ###
