"""add-energy-generation-table

Revision ID: 70ff7ad94749
Revises:
Create Date: 2026-04-02 00:19:18.373472

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70ff7ad94749"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "energy_generation",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "country_code",
            sa.Enum("ROMANIA", "HUNGARY", name="countrycode"),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.Enum("ENTSOE", "TRANSELECTRICA", name="energydataprovider"),
            nullable=False,
        ),
        sa.Column(
            "energy_source",
            sa.Enum(
                "SOLAR",
                "WIND_ONSHORE",
                "WIND_OFFSHORE",
                "HYDRO_WATER_RESERVOIR",
                "HYDRO_RUN_OF_RIVER",
                "BIOMASS",
                "GEOTHERMAL",
                "OTHER_RENEWABLE",
                "FOSSIL_GAS",
                "FOSSIL_BROWN_COAL",
                "FOSSIL_HARD_COAL",
                "FOSSIL_OIL",
                "FOSSIL_OIL_SHALE",
                "FOSSIL_COAL_DERIVED_GAS",
                "FOSSIL_PEAT",
                "NUCLEAR",
                "BATTERY_STORAGE",
                "HYDRO_PUMPED_STORAGE",
                "WASTE",
                "OTHER",
                name="energysource",
            ),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("generation_mw", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint(
            "timestamp", "country_code", "provider", "energy_source"
        ),
    )

    op.execute("SELECT create_hypertable('energy_generation', 'timestamp')")

    op.create_index(
        "idx_provider_source_time_country",
        "energy_generation",
        [
            "provider",
            "energy_source",
            "country_code",
            sa.literal_column("timestamp DESC"),
        ],
        unique=True,
    )
    op.create_index(
        op.f("ix_energy_generation_timestamp"),
        "energy_generation",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE countrycode")
    op.execute("DROP TYPE energyprovider")
    op.execute("DROP TYPE energysource")
    op.drop_index(
        op.f("ix_energy_generation_timestamp"), table_name="energy_generation"
    )
    op.drop_index("idx_provider_source_time_country", table_name="energy_generation")
    op.drop_table("energy_generation")
    # ### end Alembic commands ###
