"""added-energy-load

Revision ID: adaa0efe724c
Revises: 70ff7ad94749
Create Date: 2026-05-08 22:41:49.231090

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM  # <-- 1. CRITICAL IMPORT

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adaa0efe724c"
down_revision: Union[str, Sequence[str], None] = "70ff7ad94749"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "energy_load",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "country_code",
            # 2. USE THE POSTGRES ENUM, NOT sa.Enum
            ENUM(
                "ROMANIA",
                "HUNGARY",
                name="countrycode",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "provider",
            # 2. USE THE POSTGRES ENUM, NOT sa.Enum
            ENUM(
                "ENTSOE",
                "TRANSELECTRICA",
                name="energydataprovider",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("load_mw", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("timestamp", "country_code", "provider"),
    )
    op.create_index(
        "idx_energy_load_provider_time_country",
        "energy_load",
        ["provider", "country_code", sa.text("timestamp DESC")],
        unique=True,
    )
    op.create_index(
        op.f("ix_energy_load_timestamp"), "energy_load", ["timestamp"], unique=False
    )
    op.execute("SELECT create_hypertable('energy_load', 'timestamp')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_energy_load_timestamp"), table_name="energy_load")
    op.drop_index("idx_provider_source_time_country", table_name="energy_load")
    op.drop_table("energy_load")
    # ### end Alembic commands ###
