services:
  database:
    image: timescale/timescaledb:2.26.4-pg18
    container_name: timescaledb
    environment:
      - POSTGRES_USER=sebastian
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=carbon_intensity_forecasting
    ports:
      - 5432:5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9.14.0
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.dev
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      - database
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.12.0
    container_name: mlflow
    ports:
      - 5000:5000
    depends_on:
      - database
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    restart: unless-stopped
    command: >
      sh -c "pip install psycopg2-binary && 
      mlflow server 
      --backend-store-uri postgresql://sebastian:admin@database:5432/mlflow
      --artifacts-destination /mlflow/artifacts 
      --host 0.0.0.0 
      --port 5000
      --serve-artifacts"

volumes:
  timescaledb_data:
  mlflow_artifacts:
